
//In the following example, the code in the loop will run, 
//over and over again, as long as a variable (i) is less than 10:

let i = 0;

while (i < 10) {
	console.log(i);
	i++;
  }

// Take a look at its flowchart in the readme file.


//In this example, we want to iterate as long as the random 
//number generated by Math.random() function is odd. 

let iterations = 0;
let die;
while (iterations < 10){
	
	die = Math.ceil(Math.random() * 10);

	if (die % 2 == 0){
		break;
	}
	iterations ++;
}
console.log("Number of iterations: ", iterations + 1);
console.log("Die value: ", die);


//The continue statement breaks one iteration (in the loop), 
//if a specified condition occurs, and continues with the next iteration in the loop.
let text = "";
for (let i = 0; i < 10; i++) {
	if (i === 3) { continue; }
	text = "The number is " + i;
	console.log(text);
  }






